data_source:
  base_url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/
database:
  database_name: your_database
  host: localhost
  password: your_password
  port: 3306
  type: mysql
  username: your_username
logging:
  log_file: logs/logfile.log
  log_level: INFO
paths:
  download_path: data/download/
  extract_path: data/extract/
  transformed_path: data/cleaned/
performance:
  read_chunk_size: 10000
  write_chunk_size: 10000
settings:
  ask_user: true
  estabelecimentos_apta_only: false
