data_source:
  base_url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/
database:
  # Change the values below to match your database configuration
  database_name: my_database
  host: db_host
  password: db_password
  port: db_port
  type: mysql  # DEFAULT: mysql
  username: db_user
logging:
  log_level: INFO
  log_path: logs/
paths:
  download_path: data/download/
  extract_path: data/extract/
  transformed_path: data/cleaned/
performance:
  read_chunk_size: 10000  # DEFAULT: 10000
  write_chunk_size: 10000  # DEFAULT: 10000
settings:
  ask_user: true  # set true to use interactive mode, false to use batch mode
  estabelecimentos_apta_only: false
