database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: ''
  database_name: brazil_cnpj
# database:
#   type: mysql
#   host: localhost
#   port: 5432
#   username: your_username
#   password: your_password
#   database_name: your_database

data_source:
  base_url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj/
  zip_file_path: /path/to/downloaded/zipfile.zip

performance:
  read_chunk_size: 10000
  write_chunk_size: 10000

paths:
  download_path: data/zip/
  extract_path: data/csv/
  transformed_path: data/csv/transformed/

logging:
  log_file: /path/to/logfile.log
  log_level: INFO